#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s "$SCRIPT_DIR"/bin/irr-apply /usr/bin/
ln -s "$SCRIPT_DIR"/bin/irr-update-database /usr/bin/
ln -s "$SCRIPT_DIR"/dispatcher /etc/NetworkManager/dispatcher.d/90-ir-router

mkdir -p /var/lib/ir-router

echo "IRR_GATEWAY_IP=auto" > /var/lib/ir-router/config
echo "IRR_GATEWAY_INTERFACE=eth0" >> /var/lib/ir-router/config

irr-update-database